"""fixed relationship error between facilities and other tables

Revision ID: d91b52492ed1
Revises: 1d50fb095d38
Create Date: 2023-03-01 17:23:28.055308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91b52492ed1'
down_revision = '1d50fb095d38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('open_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=True),
    sa.Column('openingTime', sa.Integer(), nullable=True),
    sa.Column('closingTime', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('open_time')
    op.drop_table('activity')
    op.drop_table('facility')
    # ### end Alembic commands ###
